safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Andrew's Blog
# host: localhost
desc: "记录一些东西"

custom:
    category:
        default: "默认分类"
        reading_notes: "读书笔记"
    categories:
      - name:  default
        title: "默认分类"

      - name:  reading_notes
        title: "读书笔记"

    scrollingLoadCount: 0                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: andrew
        email: andrew.zhyl@gmail.com
    #     disqus: your-disqus-short-name              # Disqus缩略标识
    #     gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
    #     github: your-github-account                 # GitHub账号
    #     gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    # disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
